# Applications
# Google Chrome - Web browser
# cask "google-chrome"
# Discord - Voice and text chat software
# cask "discord"
# iTerm2 - macOS Terminmal Replacement
# cask "iterm2"
# Docker - Pack, ship and run any application as a lightweight container
# cask "docker"
# Rectangle - Move and resize windows in macOS using keyboard shortcuts or snap areas
# cask "rectangle"

# Fonts
# brew "homebrew/cask-fonts"
# subversion - Version control system designed to be a better CVS
# (required for the font installation)
brew "svn"

brew "git"
brew "neovim"
brew "tmux"
brew "awscli"
brew "asdf"
brew "tealdeer"
brew "direnv"
brew "stow"
brew "ripgrep"
