# frozen_string_literal: true

# vim: filetype=ruby

# Taps are essentially repos where we can source tools/apps from
taps = %w[homebrew/cask-fonts]
native_apps = [
  'alacritty',
  'authy',
  'cloudflare-warp',
  'discord',
  'docker',
  'firefox',
  'iterm2',
  'notion',
  'rectangle',
  'slack',
  'spotify',
  'zoom',
  # The following require cask-fonts
  'font-iosevka-nerd-font',
  'font-jetbrains-mono-nerd-font',
  'font-ubuntu-mono-nerd-font'
]
tools = %w[
  asdf
  awscli
  direnv
  fzf
  gh
  git
  gnupg
  jq
  libpq
  neovim
  ripgrep
  stow
  subversion
  tealdeer
  terraform
  tmux
  zoxide
  zsh-autosuggestions
]

taps.each { |source| tap source }
native_apps.each { |app| cask app }
tools.each { |tool| brew tool }
