# git clone https://github.com/catppuccin/alacritty.git ~/.config/alacritty/catppuccin
[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env] # This section sets env vars on launch
TERM = "xterm-256color"

[window] # semi-transparent, minimalist look
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true

[window.padding]
x = 25
y = 20

[font]
size = 14

[font.normal]
family = "ZenbonesBrainy Nerd Font Mono"
style = "Regular"

[font.bold]
family = "ZenbonesBrainy Nerd Font Mono"
style = "ExtraBold"

[font.bold_italic]
family = "ZenbonesBrainy Nerd Font Mono"
style = "ExtraBold Italic"

[font.italic]
family = "ZenbonesBrainy Nerd Font Mono"
style = "Medium Oblique"

[mouse]
hide_when_typing = true

[cursor.style]
blinking = "On"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
]
